name: CI-Diabetes-Prediction-Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  automation-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Source Code Repo
        uses: actions/checkout@v3

      - name: Konfigurasi Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mlflow scikit-learn pandas numpy matplotlib seaborn flask requests

      # Langkah 1: Jalankan training (Menghasilkan folder mlruns)
      - name: Run Training Python
        working-directory: ./Workflow-CI/MLProject
        run: |
          python modelling.py

      # Langkah 2: Jalankan Serving API buatan kita di background
      - name: Start Inference Serving API
        working-directory: ./Workflow-CI/MLProject
        run: |
          python inference.py &
          echo "Menunggu Server API Serving bangun..."
          sleep 10

      # Langkah 3: API HIT DENGAN DATA RIIL MENGGUNAKAN CURL (BUKTI EVIDENCE VALID!)
      - name: Execute API Hit with Real Data
        working-directory: ./Workflow-CI/MLProject
        run: |
          echo "--> Menyiapkan data riil dari file preprocessed..."
          # Mengambil 3 baris data asli dari csv dan merubahnya menjadi JSON format untuk di-hit ke /predict
          python -c "
          import pandas as pd, json
          df = pd.read_csv('namadataset_preprocessing/test_preprocessed.csv').head(3)
          print(json.dumps(df.to_dict(orient='records')))
          " > real_data.json
          
          echo "--> Mengirimkan data riil ke endpoint /predict via CURL..."
          curl -X POST -H "Content-Type: application/json" -d @real_data.json http://127.0.0.1:5002/predict

      # Langkah 4: Build Docker Image
      - name: Build Docker Image
        run: |
          echo -e "FROM python:3.10-slim\nRUN pip install mlflow scikit-learn pandas numpy matplotlib flask requests\nCOPY . /app\nWORKDIR /app" > Dockerfile
          docker build -t reginaa04/model-sml:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          echo "Push Sukses ke Docker Hub reginaa04!"
